require_relative 'sendgrid/client'
require_relative 'sendgrid/exceptions'
require_relative 'sendgrid/recipient'
require_relative 'sendgrid/template'
require_relative 'sendgrid/template_mailer'
require_relative 'sendgrid/mail'
require_relative 'sendgrid/response'
require_relative 'sendgrid/version'
